# Generated by Django 3.2.12 on 2022-03-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images/%Y-%m-%d/'),
        ),
    ]
