# Generated by Django 3.2.12 on 2022-04-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
