# Generated by Django 4.0 on 2021-12-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, height_field=100, upload_to='images', width_field=100),
            preserve_default=False,
        ),
    ]
