# Generated by Django 4.0 on 2022-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_rename_comment_email_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
