# Generated by Django 3.2.12 on 2022-03-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=1, max_length=200, verbose_name='Теги'),
            preserve_default=False,
        ),
    ]
