# Generated by Django 4.0 on 2021-12-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=100, upload_to='images/', width_field=100),
        ),
    ]
