# Generated by Django 4.0 on 2022-01-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
