# Generated by Django 4.0 on 2022-01-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_alter_comment_body_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ваше имя'),
        ),
    ]
