# Generated by Django 4.0 on 2022-01-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_comment_author_post_highlighted_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='story.Comment'),
        ),
    ]
