# Generated by Django 4.0 on 2022-01-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_remove_comment_post_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
