# Generated by Django 4.0 on 2022-01-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='highlighted',
        ),
    ]
