# Generated by Django 4.0 on 2022-01-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0025_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/noimage.jpg', null=True, upload_to='images/%Y-%m-%d/', verbose_name='Фото'),
        ),
    ]
